version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # only typescript 5.5 works
      - dependency-name: typescript
        versions: [">=5.6"]
      # we are using legacy config for eslint, ^9 deprecates it
      - dependency-name: eslint
        versions: ["9"]
    groups:
      deps:
        dependency-type: "production"
      deps-dev:
        dependency-type: "development"
